name = "intingpack"
author = "nouloo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87d635bfa59bbd9d0f9cc3997d4ef8acae7fdbe2d4afc46906c81f2edea14475"

[versions]
minecraft = "1.20.1"
neoforge = "47.2.18"
