name = "intingpack"
author = "nouloo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa81a84eafff46aca807e257eacb8f8826a5846f912e5690c0a35e6cca5ecff5"

[versions]
minecraft = "1.20.1"
neoforge = "47.2.18"
