name = "intingpack"
author = "nouloo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "02fc4864a07e6a423a2310a13915cbf06efa693498eecbe93b1dfa1f2810ef63"

[versions]
minecraft = "1.20.1"
neoforge = "47.2.18"
