name = "intingpack"
author = "nouloo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3656afa9444a098b99da0c646fdd24010165939934973fbbf4e39665d2ead08"

[versions]
minecraft = "1.20.1"
neoforge = "47.2.18"
