name = "intingpack"
author = "nouloo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "25ca7e33a9cb15d023ca30a727c6b35a3ffc9a53f588552e99e22e24e803e022"

[versions]
minecraft = "1.20.1"
neoforge = "47.2.18"
